### PR TITLE
FIX issue 552

### LINKED ISSUE #552: Coarray ICAR mini-app generates runtime error in caf_send_by_ref
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Defect/Bug Report #

- OpenCoarrays Version: 2.1.0 e9f7d197b9d303e995d4fa8b73b5af38f42cf39f
- Fortran Compiler: `gfortran 8.1.0` (patched)
- C compiler used for building lib: `gcc 8.1.0`
- Installation method: `install.sh`
- Output of `uname -a`: `Linux sourcery-institute-vm 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:15:38 UTC 2018 i686 i686 i686 GNU/Linux`
- MPI library being used:  MPICH 3.2
- Machine architecture and number of physical cores: x86 (4 cores)
- Version of CMake: 3.10.2

## Observed Behavior ##

`caf_send_by_ref` prints a runtime error message

## Expected Behavior ##

Program runs without error with GCC 6.4.0

## Steps to Reproduce ##
```bash
git clone https://github.com/gutmann/coarray_icar
cd src/tests
export COMPILER=gnu
mkdir ../build
make
cafrun -n 4 ./test-ideal
$ cafrun -n 4 ./test-ideal
 Number of images =            4
           1 domain%initialize_from_file('input-parameters.txt')
 ximgs=           2 yimgs=           2
 call master_initialize(this)
 call this%variable%initialize(this%get_grid_dimensions(),variable_test_val)
  Layer height       Pressure        Temperature      Water Vapor
      [m]              [hPa]             [K]            [kg/kg]
   9750.00000       271.047180       206.509430       9.17085163E-06
   7750.00000       364.236938       224.725403       7.91717321E-05
   5750.00000       481.825287       243.449936       5.01311326E-04
   3750.00000       628.424316       262.669800       2.46796524E-03
   1750.00000       809.217651       282.372711       9.08217859E-03
 ThompMP: read qr_acr_qg.dat instead of computing
 qr_acr_qg initialized:   8.90000015E-02        
 ThompMP: read qr_acr_qs.dat instead of computing
 qr_acr_qs initialized:   7.19999969E-02        
 ThompMP: read freezeH2O.dat instead of computing
 freezeH2O initialized:  0.333000004            
 qi_aut_qs initialized:   1.40000004E-02        
 
 Beginning simulation...
Fortran runtime error on image 2: libcaf_mpi::caf_send_by_ref(): unable to allocate memory on remote image.

Fortran runtime error on image 4: libcaf_mpi::caf_send_by_ref(): unable to allocate memory on remote image.

Fortran runtime error on image 1: libcaf_mpi::caf_send_by_ref(): unable to allocate memory on remote image.

Fortran runtime error on image 3: libcaf_mpi::caf_send_by_ref(): unable to allocate memory on remote image.

Error: Command:
   `/home/rouson/Desktop/Builds/opt/mpich/3.2/gnu/8.1.0-patched/bin/mpiexec -n 4 --disable-auto-cleanup ./test-ideal`
failed to run.
```
Reproducing this result takes only seconds with the if the referenced `*.dat` files are in the present working directory when the run is launched.  These can be provided upon request.  Alternatively, the program will generate them if they don't exist.  Generating them could take roughly 20-30 minutes the first time.  They will then be detected and used in subsequent runs.  I'm hoping @gutmann or @scrasmussen will report whether GCC 9 fixes this issue. If not, please add a comment in this issue with a short reproducer.

[links]:#
[Google]: https://www.google.com
[Stack Overflow]: https://stackoverflow.com
[fenced codeblocks]: https://help.github.com/articles/creating-and-highlighting-code-blocks/
[GFortran bug tracker]: https://gcc.gnu.org/bugzilla/
[Intel MPI]: https://software.intel.com/en-us/intel-mpi-library
[MPT]: http://www.sgi.com/products/software/sps.html
[MVAPICH]: http://mvapich.cse.ohio-state.edu
[MPICH]: https://www.mpich.org
[Open-MPI]: https://www.open-mpi.org
[CONTRIBUTING.md]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[Helping Out]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md#helping-out
[official release]: https://github.com/sourceryinstitute/OpenCoarrays/releases
[CMake install]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#cmake-scripts
[homebrew]: https://brew.sh
[issues page]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[mailing list]: https://groups.google.com/forum/#!forum/opencoarrays
[install.sh]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/install.sh

### PR DESCRIPTION
**Pull request by neok-m4700**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##
Currents checks for memory reallocation is incorrectly triggered by a singleton on 1st dim when referencing a coarray (delta == 1) in a derived type.

@rouson @gutmann @zbeekman Steps to Reproduce mentioned in #552 passes with the .dat files given. 

```bash
+ mpiexec -np 4 ./test-ideal
 Number of images =            4
           1 domain%initialize_from_file('input-parameters.txt')
 ximgs=           2 yimgs=           2
 call master_initialize(this)
 call this%variable%initialize(this%get_grid_dimensions(),variable_test_val)
  Layer height       Pressure        Temperature      Water Vapor
      [m]              [hPa]             [K]            [kg/kg]
   9750.00000       271.047180       206.509430       9.17085254E-06
   7750.00000       364.236786       224.725372       7.91714992E-05
   5750.00000       481.825287       243.449936       5.01311326E-04
   3750.00000       628.424316       262.669800       2.46796501E-03
   1750.00000       809.217651       282.372711       9.08217765E-03
 ThompMP: read qr_acr_qg.dat instead of computing
 qr_acr_qg initialized:  0.104000002            
 ThompMP: read qr_acr_qs.dat instead of computing
 qr_acr_qs initialized:   6.89999983E-02        
 ThompMP: read freezeH2O.dat instead of computing
 freezeH2O initialized:  0.500000000            
 qi_aut_qs initialized:   1.40000004E-02        
 
 Beginning simulation...
 Model run time:  61.352 seconds
<rest truncated ...>
```

## Rationale for changes ##

Should fix #552 
Added a regression test covering this patch.

~~WIP: please don't merge yet~~

~~EDIT 1: bug is only partially resolved, see the test case~~

~~EDIT 2: the issue seems to lie in send_for_ref ...~~

**EDIT 3: ready to merge, stop committing to this branch**

`co % a(1, :, :)[remote] = co % b(1, :, :)` => fails, I do not see (yet ?) how to fix this ...
The workaround is to use a range :
`co % a(1:1, :, :)[remote] = co % b(1:1, :, :)` => fixed by this PR
`co % a(:, :, :)[remote] = co % b(:, :, :)` => works as expected before the PR

This PR should merge without conflict from commit b09b88ef78faa4d12f02d1c098cbea140fbea30b
I known this PR is big and ugly, but without the whole cleanup,  debugging is painful.

Maybe we should also enforce **const** qualifiers, but that would be for another PR.

In addition to the TRAVIS build, I tested this PR with the following compilers:
- gcc `9.0.0` (devel - e255d1cb8f1e)
- gcc `8.1.0`
- gcc `7.3.0`
- gcc `6.4.0`

The [caf-testsuite](https://github.com/uhhpctools/caf-testsuite.git) was ran to ensure non-regression, in addition to the OpenCoarrays embedded test suite.

## Toolchain ##
gcc `8.1.0` + patches
mpich `3.2.1`
caf `2.1.0` + patches
glibc `2.27`

## Additional info and certifications ##

This pull request (PR) is a:

- [x] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

File: src/tests/regression/reported/issue-552-send_by_ref-singleton.f90 [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+   ! icar output
+   ! 3/4: Entering send_by_ref(may_require_tmp = 1, dst_type = 3).
+   ! 3/4: _gfortran_caf_send_by_ref() remote_image = 3, offset = 0, remote_mem = 0x7f4a29422060
+   ! 3/4: _gfortran_caf_send_by_ref() remote desc rank: 3 (ref_rank: 7297736)
+   ! 3/4: _gfortran_caf_send_by_ref() remote desc dim[0] = (lb = 1, ub = 1, stride = 1)
+   ! 3/4: _gfortran_caf_send_by_ref() remote desc dim[1] = (lb = 1, ub = 20, stride = 1)
+   ! 3/4: _gfortran_caf_send_by_ref() remote desc dim[2] = (lb = 1, ub = 103, stride = 20)
+   ! 3/4: _gfortran_caf_send_by_ref() extent(dst, 0): 1 != delta: 20.  ! <====== mistmatch src_cur_dim not incremented
+   ! 3/4: _gfortran_caf_send_by_ref() extent(dst, 1): 20 != delta: 101.
+
```
Comment (zbeekman) [inline src/tests/regression/reported/issue-552-send_by_ref-singleton.f90]: @neok-m4700 Can you please insert a global barrier (`sync all`) here? And then print the "Test passed." message from just the first image?

**Comment by gutmann** [comment]
This is great to see!

File: src/tests/regression/reported/issue-552-send_by_ref-singleton.f90 [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+   type(co_obj) :: co
+
+   me = this_image()
+   nimg = num_images()
+
+   if (nimg /= 2) error stop 1
+
+   allocate(co % a(1, 10, 20)[*], co % b(1, 10, 20))
+   call random_number(co % b)
+
```
Comment (zbeekman) [inline src/tests/regression/reported/issue-552-send_by_ref-singleton.f90]: While we're not actually checking the output anywhere, don't we need a synchronization here, so that a is assigned from b *after* `random_number` returns?

File: src/tests/regression/reported/issue-552-send_by_ref-singleton.f90 [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+   ! 3/4: Entering send_by_ref(may_require_tmp = 1, dst_type = 3).
+   ! 3/4: _gfortran_caf_send_by_ref() remote_image = 3, offset = 0, remote_mem = 0x7f4a29422060
+   ! 3/4: _gfortran_caf_send_by_ref() remote desc rank: 3 (ref_rank: 7297736)
+   ! 3/4: _gfortran_caf_send_by_ref() remote desc dim[0] = (lb = 1, ub = 1, stride = 1)
+   ! 3/4: _gfortran_caf_send_by_ref() remote desc dim[1] = (lb = 1, ub = 20, stride = 1)
+   ! 3/4: _gfortran_caf_send_by_ref() remote desc dim[2] = (lb = 1, ub = 103, stride = 20)
+   ! 3/4: _gfortran_caf_send_by_ref() extent(dst, 0): 1 != delta: 20.  ! <====== mistmatch src_cur_dim not incremented
+   ! 3/4: _gfortran_caf_send_by_ref() extent(dst, 1): 20 != delta: 101.
+
+   write(*, *) 'Test passed.'
```
Comment (zbeekman) [inline src/tests/regression/reported/issue-552-send_by_ref-singleton.f90]: It would be nice to ensure that `co % a(1,:,:)[2] == co % b(1,:,:)[1] .and. co % a(1,:,:)[1] == co % b(1,:,:)[2]` before marking the test as successful.

File: src/tests/regression/reported/issue-552-send_by_ref-singleton.f90 (hunk 2 above)
Comment (neok-m4700) [reply src/tests/regression/reported/issue-552-send_by_ref-singleton.f90]: @zbeekman 
Will include your changes ASAP !

**Comment by zbeekman** [comment]
FYI, test failure was on GCC 6 branch, due to #347 / #266 / #161 Re-triggered the test to see if it will pass on the second attempt, since this bug is non-deterministic

File: src/tests/regression/reported/issue-552-send_by_ref-singleton.f90 (hunk 2 above)
Comment (zbeekman) [reply src/tests/regression/reported/issue-552-send_by_ref-singleton.f90]: Amazing, cheers!

File: src/tests/regression/reported/issue-552-send_by_ref-singleton.f90 (hunk 3 above)
Comment (neok-m4700) [reply src/tests/regression/reported/issue-552-send_by_ref-singleton.f90]: Good advice, so this does not crash, but there seems to be an issue left related to rank reduction. Working on it ...

Comment (zbeekman) [reply src/tests/regression/reported/issue-552-send_by_ref-singleton.f90]: OK. If you can't fix this issue, a simpler test that doesn't trigger it, along with a new bug report would more than suffice.

File: src/mpi/mpi_caf.c [hunk 4]
```diff
@@ -2842,492 +2798,463 @@ PREFIX(send) (caf_token_t token, size_t offset, int image_index,
...
+        }
+        else
+        {
+          switch (dst_vector->u.v.kind)
+          {
+            // KINDCASE is defined above.
+            KINDCASE(1, int8_t);
+            KINDCASE(2, int16_t);
+            KINDCASE(4, int32_t);
+            KINDCASE(8, int64_t);
```
Comment (zbeekman) [inline src/mpi/mpi_caf.c]: Debug builds in [this commit](https://github.com/sourceryinstitute/OpenCoarrays/pull/555/commits/55ed8c01a1f79b79e6d97523ae2ec481b5ee77ed) fail to compile due to [errors attributed to lines 3240-3243](https://travis-ci.org/sourceryinstitute/OpenCoarrays/jobs/395903748#L1865-L1877) with [all versions of GCC/GFortran we are testing](https://travis-ci.org/sourceryinstitute/OpenCoarrays/builds/395903746):

```
/home/travis/build/sourceryinstitute/OpenCoarrays/src/mpi/mpi_caf.c:3240:25: error: expected expression before ‘int8_t’
             KINDCASE(1, int8_t);
                         ^~~~~~
# etc.
```

Something in this commit broke all the builds. I appreciate the cleanup, and would welcome it if you can resolve the issue, but I would also be content with resolving this with a `git reset HEAD^ ; git push --force`

File: src/tests/regression/reported/issue-552-send_by_ref-singleton.f90 [hunk 5]
```diff
@@ -5,29 +5,35 @@ program main
...
-   ! 3/4: _gfortran_caf_send_by_ref() remote desc dim[2] = (lb = 1, ub = 103, stride = 20)
-   ! 3/4: _gfortran_caf_send_by_ref() extent(dst, 0): 1 != delta: 20.  ! <====== mistmatch src_cur_dim not incremented
-   ! 3/4: _gfortran_caf_send_by_ref() extent(dst, 1): 20 != delta: 101.
+   sync all
+   if (any(abs(co % b(1, :, :) - co % a(1, :, :)[remote]) > epsilon(0.))) error stop 1
+   if (me == 1) write(*, *) 'Test passed.'
 
-   write(*, *) 'Test passed.'
 end program
+
```
Comment (zbeekman) [inline src/tests/regression/reported/issue-552-send_by_ref-singleton.f90]: Changes to this test [seem to have broken it](https://travis-ci.org/sourceryinstitute/OpenCoarrays/jobs/395684332#L3076) when running a debug build test with GFortran 7.3 on Ubuntu.  (The [error from the previous commit](https://travis-ci.org/sourceryinstitute/OpenCoarrays/jobs/395643539#L3334) is a different, unrelated issue.) Does it require the latest changes in GFortran 8 and >= 7.4?

File: src/mpi/mpi_caf.c (hunk 4 above)
Comment (neok-m4700) [reply src/mpi/mpi_caf.c]: Sorry, pushed too soon, fixing this issue right now.

**Comment by zbeekman** [comment]
LGTM

Thank you, oh so very much, @neok-m4700 🎉 🙇 🙏 

Without contributors like you Open Source projects like OpenCoarrays would be doomed! Thanks again for this contribution and all your hard work! 💯

**Comment by rouson** [comment]
Thanks for fixing this longstanding issue, @neok-m4700 !

**Comment by gutmann** [comment]
I finally had a chance to test this out.  While it does indeed fix the issue for 4 images, and is able to communicate with a remote image, for me this is still breaking with >64 images.  It works with 63 and 64, but breaks with 65 (and up).  I've tried a number of larger sizes up to 720 and nothing works above 64 :( I don't think this is an issue with coarray-icar code as that code base has run fine with gfortran 6.3 and cray fortran up to much larger numbers of images.  

Can anyone else reproduce this? 

```
r1i4n6:tests> mpiexec -np 65 ./test-ideal
Attaching 36339 to 685660.chadmin1

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 36431 RUNNING AT r2i1n30.ib0.cheyenne.ucar.edu
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
[proxy:0:0@r1i4n6] HYD_pmcd_pmip_control_cmd_cb (/glade/u/home/gutmann/scratch/opencoarrays/OpenCoarrays/prerequisites/downloads/mpich-3.2/src/pm/hydra/pm/pmiserv/pmip_cb.c:885): assert (!closed) failed
[proxy:0:0@r1i4n6] HYDT_dmxu_poll_wait_for_event (/glade/u/home/gutmann/scratch/opencoarrays/OpenCoarrays/prerequisites/downloads/mpich-3.2/src/pm/hydra/tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@r1i4n6] main (/glade/u/home/gutmann/scratch/opencoarrays/OpenCoarrays/prerequisites/downloads/mpich-3.2/src/pm/hydra/pm/pmiserv/pmip.c:206): demux engine error waiting for event
[mpiexec@r1i4n6] HYDT_bscu_wait_for_completion (/glade/u/home/gutmann/scratch/opencoarrays/OpenCoarrays/prerequisites/downloads/mpich-3.2/src/pm/hydra/tools/bootstrap/utils/bscu_wait.c:76): one of the processes terminated badly; aborting
[mpiexec@r1i4n6] HYDT_bsci_wait_for_completion (/glade/u/home/gutmann/scratch/opencoarrays/OpenCoarrays/prerequisites/downloads/mpich-3.2/src/pm/hydra/tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@r1i4n6] HYD_pmci_wait_for_completion (/glade/u/home/gutmann/scratch/opencoarrays/OpenCoarrays/prerequisites/downloads/mpich-3.2/src/pm/hydra/pm/pmiserv/pmiserv_pmci.c:218): launcher returned error waiting for completion
[mpiexec@r1i4n6] main (/glade/u/home/gutmann/scratch/opencoarrays/OpenCoarrays/prerequisites/downloads/mpich-3.2/src/pm/hydra/ui/mpich/mpiexec.c:344): process manager error waiting for completion
```

**Comment by gutmann** [comment]
Also, I assume this is a new bug we have stumbled across, so I can open a new issue, but I thought I would drop this here for now in case it is related still.

**Comment by neok-m4700** [comment]
@gutmann , I see some `mpich-3.2` in your path.
Can you try with mpich `3.2.1` ?
see https://github.com/sourceryinstitute/OpenCoarrays/issues/496#issuecomment-364530879

**Comment by zbeekman** [comment]
@gutmann: I know we have experienced problems with Failed images in the past, because they rely on some very new MPI features (even features that are not part of MPI-3, that are proposed for MPI-4).

It would be great if you could open a new issue (if you haven't already done so) to track this.

I would recommend trying to compile OpenCoarrays with `-DCAF_ENABLE_FAILED_IMAGES=FALSE`

Also, as pointed out by @neok-m4700 there was a bug fix in MPICH that may not be in 3.2 but definitely seems to be in 3.2.1.

**Comment by zbeekman** [comment]
Uggg it seems like maybe someone left a debug statement somewhere. I have
never seen this before. Are you building a Release configuration of
OpenCoarrays?

**Comment by gutmann** [comment]
I also found out that `dst_type` message is printed to stderr not stdout if that helps. I installed mpich 3.2.1 using the opencoarrays install script via `./install.sh -y -j4 -p mpich -I 3.2.1`.  This is using gcc 8.1, also installed via the install script.  

I think this is built as a "release" (at least that is what it prints when it is building, I didn't set anything for it.)

**Comment by gutmann** [comment]
FWIW, in opencoarrays `src/mpi/mpi_caf.c` I see `fprintf(stderr, ", dst_type = %d", dst_type);`

**Comment by gutmann** [comment]
git blame points to 250fb067864b1584836a0ad4e6076160937e809e (For whatever that is worth)

**Comment by zbeekman** [comment]
Thanks for digging. I'll investigate further once I have some time to take
a look. It's possible that it just needs a simple preprocessor conditional
wrapping or similar.

**Comment by gutmann** [comment]
Also, just to add in response to:
> It would be great if you could open a new issue (if you haven't already done so) to track this.

I think we should leave this discussion here for now as (I think) the relevant line was touched as part of this Pull Request, we can certainly move it elsewhere if you think that would be more useful.

**Comment by neok-m4700** [comment]
@gutmann Sorry, yes this was part of the huge commit where we, changed a lot of stuff. I has been fixed in my branch https://github.com/neok-m4700/OpenCoarrays/tree/perf
especially this commit https://github.com/neok-m4700/OpenCoarrays/commit/c7399d6a0e934517ccdd1450d3cf90d1cb19d906

@zbeekman 
Since this is a WIP on #556, there is no PR yet, I'm waiting updates in the comments ...

**Comment by gutmann** [comment]
Thanks, I've just commented out those lines for now and it seems to be running fine.  You all are awesome!
