### PR TITLE
Fix #682 macOS Mojave warning

### LINKED ISSUE #682: RFE: more robust GCC installation on macOS Mojave
Because macOS Mojave changed the location of some system header files that were in `/usr/include`, building GCC via  `./install.sh -p gcc` fails unless a package in `/Library/Developer/CommandLineTools/Packages/` has been installed to replace the missing files as described in this [blog post](https://solarianprogrammer.com/2017/05/21/compiling-gcc-macos/).  

Request for enhancement: update `install.sh` to detect when the files are missing and, if so, to install the necessary package (possibly via the macOS `installer` command) or at least to launch the package installation after instructing the user to relaunch the OpenCoarrays `install.sh` after the package has been installed.

### PR DESCRIPTION
**Pull request by rouson**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  coverage on master         |
|:---------------------------:|
| ![Codecov branch][coverage] |

## Summary of changes ##

Added warning output in when running the installer to build GCC on macOS Mojave or later.

## Rationale for changes ##

XCode doesn't install required headers by default so users need to know how to install them if they haven't already.

## Additional info and certifications ##

This pull request (PR) is a:

- [ ] Bug fix
- [X] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [X] I certify that:
  - I have reviewed and followed the [contributing guidelines]
  - I will wait at least 24 hours before self-approving the PR to give another
    OpenCoarrays developer a chance to review my proposed code
  - I have not introduced errant white space (no trailing white space or white space errors may
    be introduced)
  - I have added an explanation of what these changes do and why they should be included
  - I have checked to ensure there aren't other open [Pull Requests] for the same change
  - I have you written new tests for these changes
  - I have successfully tested these changes locally
  - I have commented any non-trivial, non-obvious code changes
  - The commits are logically atomic, self consistent and coherent
  - The [commit messages] follow [best practices]
  - Test coverage is maintained or increased after this is merged

## Code coverage data

coverage on master

[links]: #
[best practices]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[commit messages]: https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message
[Pull Requests]: https://github.com/sourceryinstitue/OpenCoarrays/pulls

### CODE REVIEW

**Comment by rouson** [comment]
@zbeekman  Any thoughts on why `make` [stalled] on the macOS build with `BUILD_TYPE` `InstallScript`?  It seems to have stalled on building something called `ghc`, but I don't know what that is or why it's being built.  I'm tempted to merge this because the change is pretty trivial, but the one thing that gives me pause is that it's the `InstallScript` build that stalled and this PR is for a (very minor) install script change.  Is there a way to relaunch the test to check whether the failure is repeatable?

[stalled]: https://travis-ci.org/sourceryinstitute/OpenCoarrays/jobs/594820069#L960

**Comment by zbeekman** [comment]
@rouson When you see that all tests pass except for some weird 3rd party package, please try just re-starting the single failure in the build matrix. These cases are typically just hiccups with the CI infrastructure. The problem here is that Homebrew is trying to install shellcheck, but something went amiss so it decided to try to build it from source.

Screenshot 2019-10-08 11 21 21

File: prerequisites/build-functions/build_and_install.sh [hunk 1]
```diff
@@ -5,6 +5,8 @@
 # shellcheck source=prerequisites/build-functions/edit_GCC_download_prereqs_file_if_necessary.sh
 source "${OPENCOARRAYS_SRC_DIR}/prerequisites/build-functions/edit_GCC_download_prereqs_file_if_necessary.sh"
 
+function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
```
Comment (zbeekman) [inline prerequisites/build-functions/build_and_install.sh]: It would be nice to have bash-only solutions, but this is so easy to do with awk that it's tough to make a case for replacing this.

File: prerequisites/build-functions/build_and_install.sh [hunk 2]
```diff
@@ -74,6 +76,33 @@ build_and_install()
...
 
+    # Warn about header prerequisite on macOS Mojave or subsequent versions
+    if [[ $(uname) == "Darwin" ]]; then
+      export kernel=$(uname -r)
+      export Mojave="18.7.0"
+      if [ $(version $kernel) -ge $(version $Mojave) ]; then
+        info ""
+        info "______________________________________________________________________________"
+        info "Detected Darwin $kernel >= $Mojave (Mojave).  If $package_to_build build fails"
+        info "due to a missing header (*.h) file, please try something the following bash command:"
```
Comment (zbeekman) [inline prerequisites/build-functions/build_and_install.sh]:
```suggestion
        info "due to a missing header (*.h) file, please try something like the following bash command:"
```

File: prerequisites/build-functions/build_and_install.sh (hunk 1 above)
Comment (rouson) [reply prerequisites/build-functions/build_and_install.sh]: Right.  I considered that, but the bash-only solution I found is [31 lines long] versus this one-liner and `awk` is part of the [Linux Standard Base] and [XCode] so it seems safe to assume it will always be present on the systems of interest.   Of course, performance is another matter, but as always, I'd have to see some data to choose the longer solution over the short, clear one.

[XCode]: https://developer.apple.com/xcode/features/
[31 lines long]: https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash
[Linux Standard Base]: https://en.wikipedia.org/wiki/AWK#History

**Comment by rouson** [comment]
> When you see that all tests pass except for some weird 3rd party package, please try just re-starting the single failure in the build matrix.

At last this makes sense!  I'm glad you posted the screen shot because I have many times searched for and never found that "Restart job" button. Apparently it only appears when logged into travis-ci.org.

**Comment by zbeekman** [comment]
Yes, it only appears when logged in because malicious actors could create denial of service type attacks by constantly cancelling or restarting jobs. You must have push access (or maybe more) to the repo to be able to restart.
