### PR TITLE
Pull in failed images support.

### LINKED ISSUE #309: stop_numeric, stop_string not handled correctly
See https://github.com/sourceryinstitute/opencoarrays/pull/302#discussion_r95417411 for a discussion

>stop_numeric() and stop_string() btw is not implemented correctly in caf_mpi. Both expect caf_finalize() to exit(0), which this function must not do!

### LINKED ISSUE #354: Defect: SYNC (ALL|IMAGES) w/o STAT do not error out on error
SYNC ALL and SYNC IMAGES do not error out, when an error occurs, but no STAT= is given. Standard violation section 8.5.7 (F2008) and 11.6.11 (F2015).

Reminder to self to correct this.

### PR DESCRIPTION
**Pull request by vehre**
| Avg response time                 | coverage on master         |
| --------------------------------- | ---------------------------|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage]|

## Summary of changes ##

Added failed images support.
Fixed #309.
Fixed #354.

## Rationale for changes ##

It wasn't present yet?!

## Additional info and certifications ##

This pull request (PR) is a:
 - [X] Bug fix
 - [X] Feature addition
 - [ ] Other, Please describe:

I certify that:

 - [X] I have reviewed the [contributing guidelines]
 - [X] If this PR is a work in progress I have added `WIP:` to the
       beginning of the PR title
 - [ ] If this PR is problematic for any reason, I have added
       `DO NOT MERGE:` to the beginning of the title
 - [ ] The branch name and title of this PR contains the text
       `issue-<#>` where `<#>` is replaced by the issue that this PR
       is addressing
 - [ ] I have deleted trailing white space on any lines that this PR
       touches
 - [X] I have used spaces for indentation on any lines that this PR
       touches
 - [X] I have included some comments to explain non-obvious code
       changes
 - [X] I have run the tests localy (`ctest`) and all tests pass
 - [ ] Each commit is a logically atomic, self-consistent, cohesive
       set of changes

Come on! Get a grip on all these options. My time is limited!

ATTENTION !!! Build-system work is needed !!!

For this patch to be most effective these requirements need to be added to the build system:

I propose to add a general flag to the build system, to allow the user to switch on failed_images support on demand. Additionally to this flag the following lines are needed in the build system:

if (compiler is 'gcc' and gcc-version >= 7 and mpi is 'mpich' and mpich-version >= 3.2) then
add_definition ('-DUSE_FAILED_IMAGES') to compile-statement of caf_mpi.c

// There is currently no sufficient support for openmpi or other mpi-implementations for fault tolerant  mpi. When they add support other may be added.

In the top-most CMakeList, the #ifdef WITH_FAIL_IMAGES needs to be replaced by something reasonable to switch on these tests only when failed images support is present.

I have also added another preprocessor flag 'STOP_ON_UNSUPPORTED' independent of the above to allow stopping execution when an unsupported or unimplemented feature is hit. (see caf_mpi.c at the end).

Tested with gcc-trunk (aka 8.0), gcc-6.3.1 (the failed images test are not compilable, because 6.3 does know nothing about the new functions) and mpich v3.2 on Fedora 25 x86_64.

### CODE REVIEW

**Comment by rouson** [comment]
@zbeekman, one option would be to replace the issue template with a link to the CONTRIBUTING.md file and then put the template there -- presumably at the bottom.  The link can even go directly to the template section of the CONTRIBUTING.md file.   Even though this means many people will skip it, it gives us something to reference.  When someone submits an issue but doesn't give sufficient information, we can point them to the template, close the issue, and instruct the submitter to review the template before resubmitting.

**Comment by vehre** [comment]
I propose to add a style guide document to opencoarrays, and replace all of

**Comment by vehre** [comment]
Fingers too big for smartphone screen, sorry.

What I wanted to point out is, that all of these check boxes are tedious and time consuming. I would prefer having a code style section in the contribution.md and just having to check, that I have read it and made my changes accordingly. You may even add this to the cla agreement and have it done just once per dev. There are also automatic tools out there that check the style and prevent checking code into git when it violates the style. But beware using this to strictly may stop contributions.
What i do think critical is that the style of opencoarrays and gcc differs significantly. Adding opencoarray code back to gcc is hardened by this.

**Comment by zbeekman** [comment]
> What I wanted to point out is, that all of these check boxes are tedious and time consuming. I would prefer having a code style section in the contribution.md and just having to check, that I have read it and made my changes accordingly. You may even add this to the cla agreement and have it done just once per dev. There are also automatic tools out there that check the style and prevent checking code into git when it violates the style. But beware using this to strictly may stop contributions.

I completely agree with all of this.... it's on my todo list

> What i do think critical is that the style of opencoarrays and gcc differs significantly. Adding opencoarray code back to gcc is hardened by this.

Is there a place where we can see the style guide and assess the differences? Is it a difference in our *official* style, or a difference in the style as it is in the codebase? It would be nice to adopt GCC style/practices where it makes sense to do so, however there may be some cases where it still makes sense to diverge from GCC.

**Comment by zbeekman** [comment]
@vehre: Failed images are _**NOT**_ supported in GFortran < 7, correct? If so, then it looks like I need to disable some tests when GFortran < 7.

This may take a little while for me to review... the changes are rather numerous.

**Comment by vehre** [comment]
For the gcc project in general coding conventions are here:
https://gcc.gnu.org/codingconventions.html
Unfortunately gfortran handles some of them quite relaxed.

Correct no failed images in gcc < 7, that's what I tried to tell in the 3rd and 5th paragraph from the end of the pull request description.

Some of the changes are merely style. So try to switch off taking whitespace changes into account when diffing. I tried to document anything that is unusual.

File: src/tests/unit/fail_images/image_status_test_1.f90 [hunk 1]
```diff
@@ -0,0 +1,18 @@
+! Check the status of all images. Error only, when one unexpectedly failed.
+
+program test_image_status_1
+  use iso_fortran_env , only : STAT_STOPPED_IMAGE
```
Comment (zbeekman) [inline src/tests/unit/fail_images/image_status_test_1.f90]: @vehre is there a reason you imported `STAT_STOPPED_IMAGE` but then never used it? Are you just testing if it's present?

File: src/tests/unit/fail_images/image_fail_test_1.f90 [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+  associate(np => num_images(), me => this_image())
+    if (np < 3) error stop "I need at least 3 images to function."
+
+    if (me == 2) fail image
+
+    if (me == 2) print *, "Test failed."
+
+    sync all (STAT=syncAllStat)
+    if (me == 1) print *, "Test passed."
```
Comment (zbeekman) [inline src/tests/unit/fail_images/image_fail_test_1.f90]: Should we check `syncAllStat==STAT_FAILED_IMAGE`?

File: src/tests/unit/fail_images/image_status_test_1.f90 (hunk 1 above)
Comment (zbeekman) [inline src/tests/unit/fail_images/image_status_test_1.f90]: I'm guessing this is just due to copy-paste, since it's used in other tests...

File: src/tests/unit/fail_images/image_fail_test_1.f90 (hunk 2 above)
Comment (zbeekman) [inline src/tests/unit/fail_images/image_fail_test_1.f90]: never mind, I see you have done a very nice and thorough job testing all aspects (that are currently obvious to me) of failed images! Nice work! 🎉 💯 :1st_place_medal: 🙏 🙇

**Comment by zbeekman** [comment]
This looks good to me, all that's left is to merge in the latest changes and provide some CMake logic to ensure tests are only run with GCC 7 and MPICH 3.2, as well as minor cleanups etc.

Very nice work @afanfa and @vehre 👏

File: src/tests/unit/fail_images/image_status_test_1.f90 (hunk 1 above)
Comment (vehre) [inline src/tests/unit/fail_images/image_status_test_1.f90]: Right, this is a copy'n'paste error. Just delete it.

File: src/tests/unit/fail_images/image_fail_test_1.f90 (hunk 2 above)
Comment (vehre) [inline src/tests/unit/fail_images/image_fail_test_1.f90]: We could, but I like to keep unit tests as small as necessary to test a single feature. The check whether sync all returns the correct stat-value is done in a separate test.

**Comment by rouson** [comment]
@zbeekman Any chance this can be merged this week?  I start teaching the short course at the University of Cyprus on Wednesday and would like to give the attendees an outline of what I'll cover.  I hope to introduce failed images next week.

**Comment by zbeekman** [comment]
Yes I'm close. Adding required build system stuff. Hope it will be done by
the call.

**Comment by zbeekman** [comment]
@verhe It looks like there may be a race condition or another parallelism issue: `image_fail_and_sync_test_2` seems to reliably hang if you run the test multiple times in succession: https://travis-ci.org/sourceryinstitute/OpenCoarrays/jobs/235412457#L1160

If you run with, e.g.,  `ctest --output-on-failure --repeat-until-fail 10` you might be able to trigger this on your own machine... another idea may be to try running it more oversubscribed.

**Comment by zbeekman** [comment]
@vehre: [Adding the extra synchronization](https://github.com/sourceryinstitute/OpenCoarrays/commit/3e11eac4b82b8befaf578d81ff17643570bcf1c6) in 3e11eac4b82b8befaf578d81ff17643570bcf1c6 causes `image_fail_and_sync_test_2` to pass every time now: https://travis-ci.org/sourceryinstitute/OpenCoarrays/jobs/235695125#L4287

This leads me to suspect that there is a race condition in `sync images(*, STAT=...)` when an image is failing... I think for now I'll add this to the "developer only" tests and open a new issue for it.

**Comment by zbeekman** [comment]
@verhe: Additional update: It seems that some other the other failed images tests can fail sometimes and that my attempted work around exhibits this... I'm not really sure what's going on.

Is it possible that MPI could have a bug/issue where the `-disable-auto-cleanup` flag causes some issues if a new job is launched too quickly afterwards? I'm going to push some other small commits and see if I see this behavior again or not.. if it always works the first time it is launched, perhaps MPI has a bug that is dependent on machine state. If this is the case I guess I'll put any test that fails regularly in the "developer tests" so that we can move on.

**Comment by vehre** [comment]
@zbeekman I don't have a single issue with running the testcases even multiple times. My mpi-version is mpich-3.2-6 Fedora system supplied.

As for the failing travis-run for gcc7, I suppose that it is simply timing out after 10 minutes total runtime.

**Comment by vehre** [comment]
I only see segfaults on massive oversubscription like 64 processes on a 4-core machine. I have added a commit that addresses these.

**Comment by zbeekman** [comment]
Ok, the time out is because the one test hangs for 10+ minutes, not because
the entire run takes over ten minutes. But I suspect this might be a
virtualization/cloud/MPI issue so until we get reports of others
encountering it or find a way to reliably reproduce I'm comfortable closing
the issue & merging

**Comment by zbeekman** [comment]
LGTM
