### PR TITLE
Really fix #411 on all mpi-installations reliably.

### LINKED ISSUE #411: Defect:  event post hangs using 2 images per node.
# Defect/Bug Report
Hi. When performing the following toy example for some configuration settings, the event post statement  hangs. 
For example, this happens with 4  and 8 images, only when the images are distributed in the following way: 2 images for each node.

```fortran
program prova_post
    use iso_fortran_env
    implicit none
    integer :: np, me
    type(event_type), allocatable :: snd_copied(:)[:]
 
    me=this_image()
    np = num_images()
    if (allocated(snd_copied)) deallocate(snd_copied)
    allocate(snd_copied(np)[*])
    if (me == 2)  print*,'I am  image 2, I am posting to 4'
    if (me == 2) event post(snd_copied(2)[4])
    if (me == 2) print*,' I am image 2, I have posted to 4'
    if (me == 4) event wait(snd_copied(2))
    if (allocated(snd_copied)) deallocate(snd_copied)
end program prova_post
```

- OpenCoarrays Version: 1.9.0
- Fortran Compiler: gfortran 7.1
- C compiler used for building lib: gcc 7.1
- Installation method: cmake
- Output of `uname -a`:  Linux yoda 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- MPI library being used: MPICH 3.2 
- Version of CMake: CMAKE-3.8.2

## Observed Behavior ##
```
I am  image 2, I am posting to 4
```
 (program hangs)
## Expected Behavior ##
```
I am  image 2, I am posting to 4
 I am image 2, I have posted to 4
```
## Steps to Reproduce ##
I am using a PBS script to run the program.
I have compiled the program using:
```
caf -o prova_post.x -g prova_post.f90
```
And I run it using the following script: 
```
#!/bin/bash
#PBS -l nodes=2:ppn=2,walltime=04:00:00
#PBS -N caf_prova_post
#PBS -e caf_prova_post.err
#PBS -o caf_prova_post.out
#PBS  -W x="NACCESSPOLICY:SINGLEJOB"  
cd $PBS_O_WORKDIR

cafrun -np 4./prova_post.x>prova_post.out
```

### PR DESCRIPTION
**Pull request by vehre**
|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

Really ensure progress for event_post, when CAF_MPI_LOCK_UNLOCK is set.

## Rationale for changes ##

The fix proposed in #412 does not reliably fix the issue of #411. Answering a MPI_Win_sync() with a MPI_Win_unlock() on systems that have CAF_MPI_LOCK_UNLOCK set leads to 'Unexpected synchronization of RMA calls.' or hangs of the program. Which can easily be seen by forcing setting CAF_MPI_LOCK_UNLOCK manually. This patch "answers" a MPI_Win_sync() always by the required MPI_Win_flush(). 

Furthermore does the patch add the provided testcase, reformats the touched code section according to the style guide and moves a closed regression test to a location where it can be found when searching for the testcase.

## Additional info and certifications ##

This pull request (PR) is a:

- [x] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I have reviewed the [contributing guidelines] and followed the
      policies on:
      - Pull request (PR) naming to indicate work in progress (WIP),
        and to attach the PR to the appropriate bug report, or feature
        request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Running tests locally, to ensure all of them pass
      - Maintaining or increasing test coverage
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the pull request to
        give another OpenCoarrays developer a chance to review my
        proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
Sounds great! I'm traveling until later today, so I won't be able to review those changes until then. Great that you added a test case!

File: src/mpi/mpi_caf.c [hunk 1]
```diff
@@ -4454,39 +4454,36 @@ PREFIX (event_wait) (caf_token_t token, size_t index,
 		     int until_count, int *stat,
 		     char *errmsg, int errmsg_len)
 {
-  int ierr=0,count=0,i,image=caf_this_image-1;
-  int *var=NULL,flag,old=0;
-  int newval=0;
+  int ierr = 0, count = 0, i, image = caf_this_image - 1;
+  int *var = NULL, flag, old = 0;
+  int newval = 0;
```
Comment (zbeekman) [inline src/mpi/mpi_caf.c]: I appreciate these stylistic changes, improves readability 👍

File: src/tests/unit/events/CMakeLists.txt [hunk 2]
```diff
@@ -0,0 +1,8 @@
+# Fortran tests
+
+add_executable(event_post_1 event_post_1.f90)
+target_link_libraries(event_post_1 OpenCoarrays)
+
+add_executable(event_post_2 event_post_2.f90)
```
Comment (zbeekman) [inline src/tests/unit/events/CMakeLists.txt]: We should try to get in the habit of using more descriptive names. I very much appreciate the additional test, though.

File: src/tests/unit/events/event_post_1.f90 [hunk 3]
```diff
@@ -0,0 +1,20 @@
+program event_post_1
+  use iso_fortran_env
+  implicit none
```
Comment (zbeekman) [inline src/tests/unit/events/event_post_1.f90]: A comment about what this test is actually testing would be much appreciated, along with a more descriptive name. I know you're busy so I can push commits on this branch to address this minor issue.

Comment (vehre) [inline src/tests/unit/events/event_post_1.f90]: Well the test tests event_post. Pure and easy. There is nothing more to it than whether it works or not. I liked the name, because it is just a feature test and with it the feature tested can be easily identified. What ideas for a better name do you have?

File: src/mpi/mpi_caf.c (hunk 1 above)
Comment (vehre) [inline src/mpi/mpi_caf.c]: Sorry, couldn't read myself, therefore went for adapting to the style. Should have done so in two commits, to separate stylistic from programmatic changes.

File: src/tests/unit/events/event_post_1.f90 (hunk 3 above)
Comment (zbeekman) [inline src/tests/unit/events/event_post_1.f90]: Sure, but since we have `event_post` 1 and 2 now, presumably they are testing different aspects of event post... I'll look through the code and see if I can come up with anything that distinguishes between them in a concise and meaningful way, otherwise I'll probably just leave it for now.

File: src/mpi/mpi_caf.c (hunk 1 above)
Comment (zbeekman) [inline src/mpi/mpi_caf.c]: I general, I think separating style changes from content changes is *imperative*. However, in this case, the style change was so small, and, at the same time, thoroughly discussed, in the PR text that it was impossible to confuse the two. Under most circumstances, this will probably not be the case. For this case, however, I agree that an exception can be made.

**Comment by zbeekman** [comment]
LGTM

(and Andre on call currently)

**Comment by zbeekman** [comment]
LGTM

Andre & Damian looked over this on the call
